# config/meta.yml
meta_product_name: "CookIt-up"
meta_title: "CookIt-up - Quand ton frigo te donne les recettes !"
meta_description: "Pas d'idée pour le dîner ? CookIt-up analyse ton frigo en un clin d'oeil !"
meta_image: "meta_photo.jpg" # should exist in `app/assets/images/`
