# config/meta.yml
meta_product_name: "Fridge2Plate"
meta_title: "Fridge2Plate - Discover amazing recipes"
meta_description: "You have food in your fridge but you don't know what to cook? Let us show you amazing recipes with what you have!"
meta_image: "meta_photo.png" # should exist in `app/assets/images/`
